meta:
  url:
  title:
  description:
  siteName:
  sns: ['twitter']
slide:
  chart: true
  loop: false
  ui:
    sidebar: true
    vertical: false
    pagination: # bullets | progressbar | fraction
    effect: # fade | cube | flip
  code:
    # https://prismjs.com/
    plugins: []
    theme: default # coy | dark | funky | okaidia | solarizedlight | tomorrow | twilight
    languages:
      - python
